# Generated by Django 5.1.6 on 2025-02-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tache',
        ),
    ]
