# Generated by Django 5.1.6 on 2025-02-20 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0003_tache_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='user',
        ),
        migrations.AddField(
            model_name='tache',
            name='assigne_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tache',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taches_crees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
