# Generated by Django 5.1.6 on 2025-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0005_tache_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='assigne_a',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre',
            field=models.CharField(max_length=50),
        ),
    ]
