# Generated by Django 5.1.6 on 2025-02-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_assign_tache', 'Peut assigner des tâches')]},
        ),
    ]
